### ISSUE TITLE
Traduction ?

### ISSUE THREAD

**Issue by wilfried18** [rafaelfunchal/wordpress-security-checklist#34]
How to translate your open source application correctly?
With android studio, eclipse etc.
thank you

**Comment by RafaelFunchal** [comment]
What language would you like to help with, @wilfried18 ?

**Comment by wilfried18** [comment]
French

**Comment by RafaelFunchal** [comment]
In order to translate the checklist to French, it is necessary to follow these steps:

- Add the language code `fr` to the languages array in [_config.yml](https://github.com/RafaelFunchal/wordpress-security-checklist/blob/master/_config.yml#L30);
- Create a copy of the file [items.md](https://github.com/RafaelFunchal/wordpress-security-checklist/blob/master/items.md);
- Rename it to `items.fr.md`;
- Translate whatever is necessary;
- When you're done, send me a Pull Request.

You can do so by using your favorite editor :-)
